language: c
cache:
  directories:
  - $HOME/docker-cache
before_install:
  - docker load -i $HOME/docker-cache/image.tar || true # unpack cache, tolerate failure
before_cache:
  - docker save -o $HOME/docker-cache/image.tar "${TRAVIS_REPO_SLUG##*/}" $(docker history -q "${TRAVIS_REPO_SLUG##*/}") > image.tar # pack cache
script:
  - docker build -t "${TRAVIS_REPO_SLUG##*/}" .
  - docker images
  - docker run --rm -t "${TRAVIS_REPO_SLUG##*/}" sh -c "ls /"